        <hr color=red />         日志级别：ERROR 记录时间：2020-11-08 00:12:39,971  记录类：AL.Common.API.Filters.GlobalExceptionFilter 线程ID：[4]        <br/>设备信息：{TraceId=40debb84-4174373e97a4b532, RequestId=0HM436T5MKJND:00000003, ActionName=AL.User.WebApi.Controllers.LoginController.Login (AL.User.WebApi), log4net:HostName=DESKTOP-T413THD, RequestPath=/Login/Login, ActionId=2777511e-73f0-4e20-847a-4263d7be2809, ConnectionId=0HM436T5MKJND, log4net:UserName=NOT AVAILABLE, ParentId=, log4net:Identity=NOT AVAILABLE, SpanId=|40debb84-4174373e97a4b532.}        <br/>日志信息：
 【异常类型】：Exception 	  
【异常信息】：该账号不存在 	 
 【堆栈信息】：   at AL.User.Services.UsersServices.LoginIn(String Phone, String Pwd) in G:\auroralove\auroralove_shop\auroralove_shop\AL.User\AL.User.Services\UsersServices.cs:line 36
   at AL.Common.API.AOP.InternalAsyncHelper.AwaitTaskWithPostActionAndFinallyAndGetResult[T](Task`1 actualReturnValue, Func`2 postAction, Action`1 finalAction)
   at AL.User.WebApi.Controllers.LoginController.Login(LoginRequest request) in G:\auroralove\auroralove_shop\auroralove_shop\AL.User\AL.User.WebApi\Controllers\LoginController.cs:line 50
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)           <br/>               <hr color=red />         日志级别：ERROR 记录时间：2020-11-08 00:13:55,521  记录类：AL.Common.API.Filters.GlobalExceptionFilter 线程ID：[12]        <br/>设备信息：{TraceId=40debb86-4174373e97a4b532, RequestId=0HM436T5MKJNE:00000003, ActionName=AL.User.WebApi.Controllers.LoginController.Login (AL.User.WebApi), log4net:HostName=DESKTOP-T413THD, RequestPath=/Login/Login, ActionId=2777511e-73f0-4e20-847a-4263d7be2809, ConnectionId=0HM436T5MKJNE, log4net:UserName=NOT AVAILABLE, ParentId=, log4net:Identity=NOT AVAILABLE, SpanId=|40debb86-4174373e97a4b532.}        <br/>日志信息：
 【异常类型】：Exception 	  
【异常信息】：该账号不存在 	 
 【堆栈信息】：   at AL.User.Services.UsersServices.LoginIn(String Phone, String Pwd) in G:\auroralove\auroralove_shop\auroralove_shop\AL.User\AL.User.Services\UsersServices.cs:line 36
   at AL.Common.API.AOP.InternalAsyncHelper.AwaitTaskWithPostActionAndFinallyAndGetResult[T](Task`1 actualReturnValue, Func`2 postAction, Action`1 finalAction)
   at AL.User.WebApi.Controllers.LoginController.Login(LoginRequest request) in G:\auroralove\auroralove_shop\auroralove_shop\AL.User\AL.User.WebApi\Controllers\LoginController.cs:line 50
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)           <br/>               <hr color=red />         日志级别：ERROR 记录时间：2020-11-08 00:14:25,955  记录类：AL.Common.API.Filters.GlobalExceptionFilter 线程ID：[4]        <br/>设备信息：{TraceId=40debb88-4174373e97a4b532, RequestId=0HM436T5MKJND:00000005, ActionName=AL.User.WebApi.Controllers.LoginController.Login (AL.User.WebApi), log4net:HostName=DESKTOP-T413THD, RequestPath=/Login/Login, ActionId=2777511e-73f0-4e20-847a-4263d7be2809, ConnectionId=0HM436T5MKJND, log4net:UserName=NOT AVAILABLE, ParentId=, log4net:Identity=NOT AVAILABLE, SpanId=|40debb88-4174373e97a4b532.}        <br/>日志信息：
 【异常类型】：MySqlException 	  
【异常信息】：Unknown column 'u.IsValid' in 'where clause' 	 
 【堆栈信息】：   at SqlSugar.AdoProvider.GetDataReaderAsync(String sql, SugarParameter[] parameters)
   at SqlSugar.QueryableProvider`1.GetDataAsync[TResult](KeyValuePair`2 sqlObj)
   at SqlSugar.QueryableProvider`1._ToListAsync[TResult]()
   at AL.User.Repository.UserRoleRepository.GetRoleListByUserIDs(Int32 Id) in G:\auroralove\auroralove_shop\auroralove_shop\AL.User\AL.User.Repository\UserRoleRepository.cs:line 23
   at AL.User.Services.UsersServices.LoginIn(String Phone, String Pwd) in G:\auroralove\auroralove_shop\auroralove_shop\AL.User\AL.User.Services\UsersServices.cs:line 46
   at AL.Common.API.AOP.InternalAsyncHelper.AwaitTaskWithPostActionAndFinallyAndGetResult[T](Task`1 actualReturnValue, Func`2 postAction, Action`1 finalAction)
   at AL.User.WebApi.Controllers.LoginController.Login(LoginRequest request) in G:\auroralove\auroralove_shop\auroralove_shop\AL.User\AL.User.WebApi\Controllers\LoginController.cs:line 50
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)           <br/>               <hr color=red />         日志级别：ERROR 记录时间：2020-11-08 00:15:41,268  记录类：AL.Common.API.Filters.GlobalExceptionFilter 线程ID：[5]        <br/>设备信息：{TraceId=efa70ef5-4ed5f413540241af, SpanId=|efa70ef5-4ed5f413540241af., log4net:HostName=DESKTOP-T413THD, RequestId=0HM43718K3I2B:00000001, log4net:UserName=NOT AVAILABLE, ActionId=944f86cf-133c-46d0-8425-0adee7b175ac, ParentId=, log4net:Identity=NOT AVAILABLE, ActionName=AL.User.WebApi.Controllers.LoginController.Login (AL.User.WebApi), RequestPath=/Login/Login, ConnectionId=0HM43718K3I2B}        <br/>日志信息：
 【异常类型】：MySqlException 	  
【异常信息】：Unknown column 'u.IsValid' in 'where clause' 	 
 【堆栈信息】：   at SqlSugar.AdoProvider.GetDataReaderAsync(String sql, SugarParameter[] parameters)
   at SqlSugar.QueryableProvider`1.GetDataAsync[TResult](KeyValuePair`2 sqlObj)
   at SqlSugar.QueryableProvider`1._ToListAsync[TResult]()
   at AL.User.Repository.UserRoleRepository.GetRoleListByUserIDs(Int32 Id) in G:\auroralove\auroralove_shop\auroralove_shop\AL.User\AL.User.Repository\UserRoleRepository.cs:line 23
   at AL.User.Services.UsersServices.LoginIn(String Phone, String Pwd) in G:\auroralove\auroralove_shop\auroralove_shop\AL.User\AL.User.Services\UsersServices.cs:line 46
   at AL.Common.API.AOP.InternalAsyncHelper.AwaitTaskWithPostActionAndFinallyAndGetResult[T](Task`1 actualReturnValue, Func`2 postAction, Action`1 finalAction)
   at AL.User.WebApi.Controllers.LoginController.Login(LoginRequest request) in G:\auroralove\auroralove_shop\auroralove_shop\AL.User\AL.User.WebApi\Controllers\LoginController.cs:line 50
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)           <br/>               <hr color=red />         日志级别：ERROR 记录时间：2020-11-08 00:19:17,355  记录类：AL.Common.API.Filters.GlobalExceptionFilter 线程ID：[10]        <br/>设备信息：{ParentId=, ActionName=AL.User.WebApi.Controllers.LoginController.Login (AL.User.WebApi), ActionId=e644be6a-17da-4b2f-a700-59eb61a59d64, RequestPath=/Login/Login, log4net:Identity=NOT AVAILABLE, ConnectionId=0HM4373FBD9PC, log4net:UserName=NOT AVAILABLE, RequestId=0HM4373FBD9PC:00000001, log4net:HostName=DESKTOP-T413THD, TraceId=ff93c77d-481caa01577be6a6, SpanId=|ff93c77d-481caa01577be6a6.}        <br/>日志信息：
 【异常类型】：MySqlException 	  
【异常信息】：Unknown column 'IsValid' in 'field list' 	 
 【堆栈信息】：   at SqlSugar.AdoProvider.GetDataReaderAsync(String sql, SugarParameter[] parameters)
   at SqlSugar.QueryableProvider`1.GetDataAsync[TResult](KeyValuePair`2 sqlObj)
   at SqlSugar.QueryableProvider`1._ToListAsync[TResult]()
   at AL.Common.Base.Repository.BaseRepository`1.Query(Expression`1 whereExpression)
   at AL.User.Services.UsersServices.LoginIn(String Phone, String Pwd) in G:\auroralove\auroralove_shop\auroralove_shop\AL.User\AL.User.Services\UsersServices.cs:line 33
   at AL.Common.API.AOP.InternalAsyncHelper.AwaitTaskWithPostActionAndFinallyAndGetResult[T](Task`1 actualReturnValue, Func`2 postAction, Action`1 finalAction)
   at AL.User.WebApi.Controllers.LoginController.Login(LoginRequest request) in G:\auroralove\auroralove_shop\auroralove_shop\AL.User\AL.User.WebApi\Controllers\LoginController.cs:line 50
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)           <br/>       